language: nodejs

services:
  - docker

before_script:
  - docker-compose up -d
  - sleep 15
  - bash pre-test.sh
  - npm install -g tsc
  - cd ${TRAVIS_BUILD_DIR}/car-service && npm install && tsc && cd ./dist/src/ && cp ${TRAVIS_BUILD_DIR}/car-service/.env . && nohup node main.js &
  # - cd ${TRAVIS_BUILD_DIR}/apartment-service	&& npm install && npm start
  # - cd ${TRAVIS_BUILD_DIR}/restaurant-service	&& npm install && npm start
script:
  - curl -XGET localhost:3000/api
  #- cd ${TRAVIS_BUILD_DIR}/book-trip-sec && npm run coverage && npm run test
