language: nodejs

services:
  - docker

before_script:
  - nvm install 8
  - nvm use 8
  - docker-compose up -d
  - sleep 15
  - docker exec -ti localmongo1 mongo --eval 'config={"_id":"rs0","members":[{"_id":0,"host":"localmongo1:27017"},{"_id":1,"host":"localmongo2:27017"},{"_id":2,"host":"localmongo3:27017"}]}; rs.initiate(config)'
  - bash pre-test.sh
  - npm install -g typescript@3.0
  - cd ${TRAVIS_BUILD_DIR}/car-service 
  - npm install && tsc && cd ${TRAVIS_BUILD_DIR}/car-service/dist && cp ${TRAVIS_BUILD_DIR}/car-service/.env . 
  - cd ${TRAVIS_BUILD_DIR}/car-service/dist && node main.js
  # - cd ${TRAVIS_BUILD_DIR}/apartment-service	&& npm install && npm start
  # - cd ${TRAVIS_BUILD_DIR}/restaurant-service	&& npm install && npm start
script:
  - curl -XGET localhost:3000/api
  #- cd ${TRAVIS_BUILD_DIR}/book-trip-sec && npm run coverage && npm run test
